### ISSUE TITLE
Errors after install

### ISSUE THREAD

**Issue by seekaplayer** [RobertGrubb/iratephp#5]
I completed the installation and all went well. When I load in the page and go to console log I get a ton of errors.

(index):8 GET http://localhost/localhost/iratephp/assets/css/app.css?v=1582165487 net::ERR_ABORTED 404 (Not Found)
(index):54 GET http://localhost/localhost/iratephp/assets/scripts/irate.class.js?v=1582165487 net::ERR_ABORTED 404 (Not Found)
(index):55 GET http://localhost/localhost/iratephp/assets/scripts/app.js?v=1582165487 net::ERR_ABORTED 404 (Not Found)
(index):54 GET http://localhost/localhost/iratephp/assets/scripts/irate.class.js?v=1582165487 net::ERR_ABORTED 404 (Not Found)
(index):55 GET http://localhost/localhost/iratephp/assets/scripts/app.js?v=1582165487 net::ERR_ABORTED 404 (Not Found)

When I go to the network tab this is a reference

Request URL: http://localhost/localhost/iratephp/assets/css/app.css?v=1582165582
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:80
Referrer Policy: no-referrer-when-downgrade

**Comment by RobertGrubb** [comment]
Will be looking into this soon.

**Comment by RobertGrubb** [comment]
I have once again released a fix for this, and hoping it works this time. 

In your case, @seekaplayer when you run the setup, because you are on `localhost`, and your folder is a subdomain of that, you will still need to apply a URL for your setup. It can be one of the following:

`http://localhost/iratephp` or `/iratephp`

Totally your call on how you want to handle that, but it's still a requirement. The reason being is that `$_SERVER['HTTP_HOST']` and `$_SERVER['HTTP_URI']` working together will return the url WITH the Irate Framework routes. Down the road I may advance the system to determine if there are routes in the URL, but for now, to try and speed up the development, I have simply required the base url for situations like yours. 

Thanks!
